name: Node.js CI
'on':
  push:
    branches:
      - master
      - beta
      - renovate/**
  pull_request:
    types:
      - opened
      - synchronize
env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Setup node
        uses: actions/setup-node@962678f22cdec338fba2a277a33cf81d5e28f7b9
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm clean-install
      - run: npm test
  release:
    needs:
      - verify
    uses: form8ion/.github/.github/workflows/release-package.yml@master
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
